# -- Main Menu --
# Displayed in the header at the top of the page.

[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "Categories"
  pageRef = "categories"
  weight = 40

[[main]]
  name = "About"
  pageRef = "about"
  weight = 50

# -- Footer Menu --
# Displayed at the bottom of the page, just before the copyright notice.

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 20

[[footer]]
  name = "About"
  pageRef = "about"
  weight = 30
